dist: bionic
language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.04
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.08
os:
  - linux
matrix:
  include:
    - os: linux
      env: OCAML_VERSION=4.09 EXTRA_DEPS="ocamlformat.0.11.0" PRE_INSTALL_HOOK="make format"
    - os: osx
      env: OCAML_VERSION=4.09
